**Exercicio 1**

 integrate.quad(f, 0, 3.14): Calcula a integral definida da função f(x) = x
2
sin(x) no intervalo de 0 a π.

In [ ]:
import numpy as np
from scipy import integrate

def f(x):
  return x**2 * np.sin(x)

resultado, erro = integrate.quad(f, 0, 3.14)
print("O resultado da integração é:", resultado)
print("O erro da integração é:", erro)



O resultado da integração é: 5.869604401089359
O erro da integração é: 6.516569951530559e-14


**Exercicio 2**

solve ivp: Resolve equações diferenciais ordinárias (EDOs) com condições
iniciais.

In [ ]:
from scipy.integrate import solve_ivp
import numpy as np

def eq_diferencial(x, y):
  return x - y

solucao = solve_ivp(eq_diferencial, [0, 10], [1], t_eval=np.linspace(0, 10, 100))
print("Tempo: ", solucao.t)
print("Solução pra Y: ", solucao.y[0])

Tempo:  [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.181

**Exercicio 3**

root(f, 2): Encontra a raiz da funçãoo f(x) = 0 partindo de uma aproximação inicial x = 2.

In [ ]:
from scipy.optimize import root
def f(x):
  return x**4 - 3*x**3 + 2
solucao = root(f, 2)
print("Raiz encontrada: ", solucao.x)


Raiz encontrada:  [1.]


**Exercicio 4**

minimize(f, 0): Busca o valor de x que minimiza a funçõa, partindo de
uma estimativa inicial x = 0.
Como não tem maximiza então tem que inverter o sinal da função

In [ ]:
from scipy.optimize import minimize
def f(x):
  return -x**2 + 4*x + 1
def f_negativo(x):
  return -f(x)
solucao = minimize(f_negativo, 0)
print("Máximo encontrado: ", solucao.x)

Máximo encontrado:  [2.00000003]


**Exercicio 5**

 fft(sinal): Calcula a transformada de Fourier do sinal f(t).

In [46]:
from scipy.fft import fft
import numpy as np

t = np.linspace(0, 1, 50)
sinal = np.sin(2*np.pi*t) + np.cos(4* np.pi * t)
transformada = fft(sinal)
print("Sinal:", sinal)
print (" Transformada de Fourier :", transformada )

Sinal: [ 1.00000000e+00  1.09517202e+00  1.12497329e+00  1.09361635e+00
  1.00911012e+00  8.82638117e-01  7.27734128e-01  5.59310549e-01
  3.92604473e-01  2.42111733e-01  1.20579748e-01  3.81260364e-02
  1.54082345e-03  1.38199560e-02  7.39590443e-02  1.77022464e-01
  3.14482646e-01  4.74807200e-01  6.44254971e-01  8.07828290e-01
  9.50318244e-01  1.05737354e+00  1.11652184e+00  1.11807539e+00
  1.05586023e+00  9.27719794e-01  7.35758129e-01  4.86305404e-01
  1.89606063e-01 -1.40751558e-01 -4.88628500e-01 -8.36301023e-01
 -1.16553731e+00 -1.45871597e+00 -1.69991438e+00 -1.87589678e+00
 -1.97693827e+00 -1.99743161e+00 -1.93623753e+00 -1.79675596e+00
 -1.58671351e+00 -1.31768105e+00 -1.00435242e+00 -6.63630973e-01
 -3.13582944e-01  2.76750163e-02  3.43082345e-01  6.17664120e-01
  8.39417701e-01  1.00000000e+00]
 Transformada de Fourier : [ 1.        -0.00000000e+00j  2.86530644-2.45984768e+01j
 24.90097454+3.84183981e+00j -0.91350596+2.19103157e-01j
 -0.40569752+1.80146383e-01j -0.253710

**Exercicio 6**

Cria a Matriz em seguida usa linalg.inv para inverter

In [7]:
import numpy as np
from scipy import linalg

matriz = np.random.randint(1, 101 ,(5,5))
inversa = linalg.inv(matriz)
print("Matriz Original: ", matriz)
print("Inversa da Matriz: ", inversa)


Matriz Original:  [[86  1 83 44 69]
 [72 19 87  4 81]
 [75 83 61 25 22]
 [49 75  3 83 38]
 [24 88 51 23 80]]
Inversa da Matriz:  [[-0.02892459  0.04201219  0.00166178  0.02050873 -0.02778852]
 [-0.00793453  0.00036527  0.00676828  0.00100403  0.00413551]
 [ 0.03992308 -0.04731196  0.01072467 -0.0288235   0.02421159]
 [ 0.03050098 -0.03601778 -0.00082635 -0.00577511  0.01313133]
 [-0.01681463  0.02751104 -0.01454304  0.01277827 -0.00292265]]
Matriz x Inversa (deve ser ~identidade):
 [[ 1.  0.  0. -0.  0.]
 [-0.  1.  0.  0. -0.]
 [ 0.  0.  1. -0.  0.]
 [-0.  0. -0.  1.  0.]
 [ 0.  0. -0. -0.  1.]]


**Exercicio 7**

interpolate.interp1d: Cria uma função de interpolação cubica com base
nos pontos dados.

In [13]:
from scipy import interpolate
import numpy as np
matriz = [[0,0], [1,2], [2,3], [3,5], [4,4]]
matriz_np = np.array(matriz)

f_interpolda = interpolate.interp1d(matriz_np[:,0], matriz_np[:,1], kind='cubic')
array = np . array ([0.5 , 1.5 , 2.5 , 3.5])
valores_interpolados = f_interpolda(array)
print("Valores Interpolados: ", valores_interpolados)

Valores Interpolados:  [1.34375 2.40625 4.03125 5.21875]


**Exercicio 8**

 linalg.solve(A, B): Resolve sistemas lineares da forma Ax = B.


In [14]:
from scipy import linalg
import numpy as np

A = np.array([[3, 2], [1, 4]])
B = np.array([5, 6])
solucao = linalg.solve(A, B)
print("Solução do sistema: ", solucao)

Solução do sistema:  [0.8 1.3]


**Exercicio 9**

curve fit: Ajusta a curva com base nos dados fornecidos e na função
modelo. Aqui ajustamos uma parábola.


In [16]:
from scipy.optimize import curve_fit
import numpy as np
matriz = [[1,2], [2,4], [3,5], [4,7], [5,8]]
matriz_np = np.array(matriz)

def curva_quadrada(x, a, b, c):
    return a*x**2 + b*x + c

parametros, _ = curve_fit(curva_quadrada, matriz_np[:,0], matriz_np[:,1])
print("Parâmetros da curva quadrática: ", parametros)

Parâmetros da curva quadrática:  [-0.07142857  1.92857143  0.2       ]


**Exercicio 10**

.dblquad calcula o valor numérico de uma integral dupla

In [51]:
from scipy.integrate import dblquad

def f(y, x):
    return x*y + x**2

resultado= dblquad(f, 0, 2, 0, 1)

print("Resultado da integral dupla:", resultado)



Resultado da integral dupla: (3.666666666666667, 5.5294392329864537e-14)


**Exercicio 11**

linalg.eig retorna dois arrays, autovalores e autovetores

In [21]:
from scipy import linalg
import numpy as np
matriz = np.random.randint(1, 101, (4, 4))

autovalores, autovetores = linalg.eig(matriz)
print("Matriz: ", matriz)
print("Autovalores: ", autovalores.real)
print("Autovetores: ", autovetores)

Matriz:  [[87  4 95 92]
 [ 8 20 40 22]
 [79 37 45 56]
 [96 38 15 43]]
Autovalores:  [218.35070107 -49.05694175  28.32862362  -2.62238295]
Autovetores:  [[ 0.70020669  0.61209057  0.36870683 -0.36529923]
 [ 0.18257024  0.26937957 -0.85636828  0.12741042]
 [ 0.50874595 -0.19250579 -0.33144074 -0.44362233]
 [ 0.46642927 -0.71813739  0.14434572  0.80840725]]


**Exercicio 12**

mesma logica do exescicio 3 só usando np.exp para replesentar o e^x

In [25]:
from scipy.optimize import root
import numpy as np
def f(x):
  return np.exp(x) - x**2
solucao = root(f, 0)
print("Raiz encontrada: ", solucao.x)


Raiz encontrada:  [-0.70346742]


**Exercicio 13**

Usei det para encontar o determinante

In [30]:
from scipy.linalg import det
import numpy as np
matriz = np.random.randint(-10, 11, (6, 6))
print(matriz)
print("Determinante:", det(matriz))

[[ 4  4 -7  0  7  4]
 [ 3  5 -9 -7  0 -9]
 [ 6 -6 -9 -7  8  7]
 [-6  3  8 -3 10 -2]
 [ 6 -2 -9 -2  5 -1]
 [ 7 -3 -8 -4 -5 -3]]
Determinante: -270478.9999999999


**Exercicio 14**

minimize: Minimiza funções multivariadas,

In [34]:
from scipy.optimize import minimize

def f(v):
  x, y = v
  return (x -2)**2 + (y-3)**2
resultado = minimize(f, [0, 0])
print("Solução:", resultado.x)

Solução: [1.99999999 2.99999999]


**Exercicio 15**

ifft é a função de transformada inversa do módulo scipy.fft (equivalente a fft, mas para o caminho inverso).

In [44]:
from scipy.fft import fft, ifft
import numpy as np
tamanho = 10
sinal = np.random.randn(tamanho) + 1j * np.random.randn(tamanho)
transformada = ifft(sinal)
print("Sinal:", sinal)
print("Transformada de Fourier:", transformada)

Sinal: [ 0.71136079+0.23939667j -0.20679325-2.10229639j -0.5757144 -1.1684853j
 -0.33372703-0.44733884j -1.15293284-0.42819213j  1.93949348+0.41861567j
  0.57233643+0.25840931j -0.68873473-0.37475144j -0.1765355 -0.82001539j
  1.65590733+3.08616356j]
Transformada de Fourier: [ 0.17446603-0.13384943j  0.43511614-0.17573023j  0.87986944+0.26093894j
  0.32660704-0.29784695j  0.37835388-0.02326221j -0.29876313-0.24992794j
 -0.09839535-0.15056101j -0.74139779+0.37943283j -0.00886687+0.37573988j
 -0.33562861+0.25446279j]


**Exercicio 16**

Use a mesma recla do exercio 2, só que antes transformar a equação de segunda ordem num sistema de duas equações de primeira ordem.

In [48]:
from scipy.integrate import solve_ivp
import numpy as np

def eq_diferencial(t, y):
  y0, y1 =y
  dy0_dt = y1
  dy1_dt = -y0
  return [dy0_dt, dy1_dt]
avaliacao = np.linspace(0, 10, 100)
solucao = solve_ivp(eq_diferencial, [0, 10], [1, 0], t_eval=avaliacao)
print("Tempo:", solucao.t)
print("Solução para y0:", solucao.y[0])
print("Solução para y1:", solucao.y[1])



Tempo: [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.1818

**Exercicio 17**

Usei root para encontrar a Raiz cubica que nem anteriormente

In [50]:
from scipy.optimize import root

def f(x):
  return x**3 - 27
solucao = root(f,1)
print("Raiz cubica de 27: ", solucao.x)

Raiz cubica de 27:  [3.]


**Exercicio 18**

usando interpolate.interp1d para interplorar os valores da função

In [52]:
from scipy import interpolate
import numpy as np
def f(x):
  return x**2
array = np.array([1,2,3,4,5])
y = f(array)

f_interpolda = interpolate.interp1d(array, y, kind='cubic')
valores_interpolados = f_interpolda(array)
print("Valores Interpolados: ", valores_interpolados)

Valores Interpolados:  [ 1.  4.  9. 16. 25.]


**Exercicio 19**

mesma logica aou usar fft anteriormente

In [54]:
from scipy.fft import fft
import numpy as np

t = np.linspace(0, 1, 50)
sinal = np.sin(2*np.pi*t) + np.cos(4* np.pi * t)
transformada = fft(sinal)
print("Sinal:", sinal)
print (" Transformada de Fourier :", transformada )

Sinal: [ 1.00000000e+00  1.09517202e+00  1.12497329e+00  1.09361635e+00
  1.00911012e+00  8.82638117e-01  7.27734128e-01  5.59310549e-01
  3.92604473e-01  2.42111733e-01  1.20579748e-01  3.81260364e-02
  1.54082345e-03  1.38199560e-02  7.39590443e-02  1.77022464e-01
  3.14482646e-01  4.74807200e-01  6.44254971e-01  8.07828290e-01
  9.50318244e-01  1.05737354e+00  1.11652184e+00  1.11807539e+00
  1.05586023e+00  9.27719794e-01  7.35758129e-01  4.86305404e-01
  1.89606063e-01 -1.40751558e-01 -4.88628500e-01 -8.36301023e-01
 -1.16553731e+00 -1.45871597e+00 -1.69991438e+00 -1.87589678e+00
 -1.97693827e+00 -1.99743161e+00 -1.93623753e+00 -1.79675596e+00
 -1.58671351e+00 -1.31768105e+00 -1.00435242e+00 -6.63630973e-01
 -3.13582944e-01  2.76750163e-02  3.43082345e-01  6.17664120e-01
  8.39417701e-01  1.00000000e+00]
 Transformada de Fourier : [ 1.        -0.00000000e+00j  2.86530644-2.45984768e+01j
 24.90097454+3.84183981e+00j -0.91350596+2.19103157e-01j
 -0.40569752+1.80146383e-01j -0.253710

**Exercicio 20**

novamento usando linalg.solve para resolver só que dessa ves com três variaveis

In [55]:
from scipy import linalg
import numpy as np

A = np.array([[3, 2, -9], [1, -4, 7], [3, -8, 5]])
B = np.array([5, 6, 2])
solucao = linalg.solve(A, B)
print("Solução do sistema(x, y, z): ", solucao)

Solução do sistema(x, y, z):  [4.88461538 2.61538462 1.65384615]
