**Exercıcio 1**

usei np.random.randint para criar um array de numeros aleatorios


In [ ]:
import numpy as np

array = np.random.randint(10, 101, size=50)
print("Array de 50 valores aleatórios entre 10 e 100:\n", array)


Array de 50 valores aleatórios entre 10 e 100:
 [ 80  16  18  97  31  80  41  52  61  57  56  83 100  16  84  13  73  59
  96  60  35  69  85  88  52  19  54  32  15  58  72  64  87  77  54  27
  80  92  26  59  36  19  45  86  88  41  30  34  73  96]


 **Exercicio 2**

In [ ]:
import numpy as np

matrix_identidade = np.eye(4)
print("Matriz identidade 4x4:\n", matrix_identidade)

Matriz identidade 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Exercicio 3**

Usei np.zeros, para gerar um arrray de zeros depois só mudei os numeros depois

In [ ]:
import numpy as np
array_zeros = np.zeros(15)
array_zeros[4:10] = 1
print(array_zeros)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


**Exercicio 4**
Criei o array depis só usei as função para encontar a media e a moda

In [3]:
import numpy as np
from scipy.stats import mode
array = np.random.randint(1,101, size=100)
media =np.mean(array)
moda = mode(array)[0]
print("Array de 100 valores aleatórios entre 1 e 100:\n", array)
print("Média:", media)
print("Moda:", moda)


Array de 100 valores aleatórios entre 1 e 100:
 [ 44  20  79  97  91  93  24  71  59  62  11  54   1  66  44  63  23  81
  61  52  17  66  23  37  27  65  33  91  41  39  98  95  96  94  12  93
  29  10  91  97   6  21  34  90   3   9  65  34 100   2  38  52  95   3
   5  36  78  20  77 100   9  97  48  10  49 100  89  27  24  24  22  74
  83  11  60  64  74  91  12  59  39  37  47  11  41  37  64  95   7  51
  28  89  33  96  45  17 100  46  66  74]
Média: 51.68
Moda: 91


**Exercicio 5**

Cria um array depois cria uma mascara booleana para então substituir o valor

In [ ]:
import numpy as np
array = np.random.randint(1,101, size=20)
array[array % 3 == 0] = -3
print(array)

[22 58 53 14 -3 -3 91 65 62 40  4 91 50 25  1 -3 -3 82 22  4]


**Exercicio 6**

In [ ]:
import numpy as np
matriz = np.random.rand(5,5)
soma = np.sum(matriz)
print("Matriz 5x5:\n", matriz)
print("Soma dos elementos da matriz:", soma)
#

Matriz 5x5:
 [[0.22122881 0.10709108 0.28879898 0.46939304 0.01794428]
 [0.34626721 0.39555272 0.82403083 0.94433389 0.69687378]
 [0.43885007 0.45733372 0.86598408 0.51270014 0.83569521]
 [0.61272874 0.07381432 0.34977573 0.41183291 0.23740667]
 [0.23611562 0.24420464 0.21211319 0.11370196 0.65439654]]
Soma dos elementos da matriz: 10.56816815323611


**Exercicio 7**

Cria os dois array depois pega o coeficiente de correlação

In [10]:
import numpy as np
array1 = np.random.randint(1,10,10)
array2 = np.random.randint(1,10,10)
correlacao = np.corrcoef(array1, array2)
correlacao = np.round(correlacao,2)
valor_correlacao = correlacao[0, 1]
print("Array 1:", array1)
print("Array 2:", array2)
print("Matriz completa:\n", correlacao)
print(f"Correlação entre os arrays: {valor_correlacao}")

Array 1: [7 3 2 5 5 8 9 1 4 9]
Array 2: [6 1 9 4 1 7 1 7 8 1]
Matriz completa:
 [[ 1.   -0.44]
 [-0.44  1.  ]]
Correlação entre os arrays: -0.44


**Exercicio 8**

Ciar a matriz 3x3 de numeros inteiros depois elevios ao quadrado

In [ ]:
import numpy as np
matriz = np.random.randint(1,10, (3,3))
matriz_quadrada = matriz ** 2
print("Matriz original:\n", matriz)
print("Matriz quadrada: \n", matriz_quadrada)

Matriz original:
 [[2 6 8]
 [5 1 1]
 [4 2 4]]
Matriz quadrada: 
 [[ 4 36 64]
 [25  1  1]
 [16  4 16]]


**Exercicio 9**

Cria um array depois faz um calculo utilizando o np.ptp(array) que calcula o maximo menos o minimo


In [23]:
import numpy as np

array = np.random.randint(1,10,10)
print(array)

array_normalizado = (array - array.min()) / np.ptp(array)
print(array_normalizado)

[5 8 4 4 7 8 7 4 5 9]
[0.2 0.8 0.  0.  0.6 0.8 0.6 0.  0.2 1. ]


**Exercicio 10**

Cria a Matriz em seguida usa o np.fill_diagonal para  substitui os elementos da diagonal

In [29]:
import numpy as np

matriz = np.eye(6,6)
np.fill_diagonal(matriz, np.arange(1,7))
print(matriz)


[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


**Exercicio 11**

Gera 100 numeros aleatorios, use np.unique para retorna dois arrays, um com valores unicos e outro com quantas vezes cada valor único aparece
depois ver qual se repete mais

In [35]:
import numpy as np
array = np.random.randint(1, 100, size=100)
valores_unicos, contagem = np.unique(array, return_counts=True)
indice = np.argmax(contagem)
valor_mais_frequente = valores_unicos[indice]
quantidade = contagem[indice]
print(array)
print("numero que mais se repete ", valor_mais_frequente)
print("quantidade de vezes que se repete", quantidade)



[65 41 32 62 11 15 35 25 47  7 61 89 22  5 58 83 85 34 84 67 46 69 30 60
 54 63 94 74 19  5 36 87 64 79 81 55 26 88 71 18 24 88 61  2 53 75 12 25
 34  9 62 71 44  1 49 75 99 28 28 30 21 84  8 55 94 82 77 41 87 74 18 11
 36 29  2 13 67 17 43 42 78 51 67 90 51  3 48 28 66 76 50 91 61 83  9  1
 78 74 75 51]
numero que mais se repete  28
quantidade de vezes que se repete 3


**Exercicio 12**

Mesma logica do exercicio 10

In [36]:
import numpy as np

matriz = np.eye(4,4)
np.fill_diagonal(matriz, 7)
print(matriz)

[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


**Exercicio 13**

Gera os array com 10 numeros pares depois use a função certa é np.cumsum para fazer a soma acumulativa

In [40]:
import numpy as np
array = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
soma = np.cumsum(array)
print(array)
print(soma)

[ 2  4  6  8 10 12 14 16 18 20]
[  2   6  12  20  30  42  56  72  90 110]


**Exercicio 14**

Gera os dois array calcula a diferença e usa a função para pegar a media

In [47]:
import numpy as np
array1 = np.random.randint(1,10,10)
array2 = np.random.randint(1,10,10)

diferenca = array1 - array2
media = np.mean(diferenca)
print(array1)
print(array2)
print(diferenca)
print(media)


[4 5 3 1 7 2 7 5 6 1]
[7 9 3 4 1 6 9 7 3 9]
[-3 -4  0 -3  6 -4 -2 -2  3 -8]
-1.7


**Exercicio 15**

mesma logica do exercicio 5, só substituindo os maiores de 50

In [49]:
import numpy as np
array = np.random.randint(1, 101, 20)
array[array > 50] = 50
print(array)

[13 40 50 28 50 25  7 50 50  1 38 26 39 32 50 50 13 34 50 50]


**Exercicio 16**

cria um array de 12 numeros e ussa .reshape para reorganizar o array em uma matriz 3x4

In [ ]:
import numpy as np
array = np.arange(1, 13)
matriz = array.reshape(4, 3)
print(matriz)

**Exercicio 17**

Crie a Matriz 4x4, depois outra matriz representado as posiçõe depois multiplique

In [53]:
import numpy as np
matriz = np.random.randint(1,10, (4,4))
posicao = np.arange(16).reshape(4,4)

resultado = matriz * posicao
print(matriz)
print(resultado)


[[9 6 3 8]
 [6 9 3 3]
 [9 2 6 3]
 [3 7 7 5]]
[[ 0  6  6 24]
 [24 45 18 21]
 [72 18 60 33]
 [36 91 98 75]]


**Exercicio 18**

Mesma logica de exercicos anteriores

In [60]:
import numpy as np
array = np.random.randint(1,101, size=10)
novo_array = array.copy()
novo_array[array % 5 == 0] = 0
print(array)
print(novo_array)

[81 95 84 15 43 15 46 33 76  8]
[81  0 84  0 43  0 46 33 76  8]


**Exercicio 19**

Usar as diferentes funçõs para encontra o cosseno e inverter em radianos depois converter para graus

In [62]:
import numpy as np
array1 = np.random.randint(1,101, size=20)
array2 = np.random.randint(1,101, size=20)
pridutorio = np.dot(array1, array2)
norma1 = np.linalg.norm(array1)
norma2 = np.linalg.norm(array2)
angulo_rad = np.arccos(pridutorio / (norma1 * norma2))
angulo_graus = np.degrees(angulo_rad)
print(array1)
print(array2)
print(pridutorio)
print(angulo_rad)
print(angulo_graus)

[83 57 71 49 40 28 24 71 48 45 45 57 41 16 61 10 52 61 56 37]
[23 66 15 24  8 67 44 51 41 87 66 24 54 42 44 13 30 59 74 76]
42821
0.5926057738422242
33.95380975624361


**Exercicio 20**

Crie a Matriz depois utiliza o axis=1 para percorrer a linha e encontra o menor valor

In [63]:
import numpy as np
matriz = np.random.randint(1,101, (5,5))
minimo = np.min(matriz, axis=1)
print(matriz)
print(minimo)


[[ 97  66  28  56  24]
 [100  68  38  83  11]
 [ 23  27  58  15  51]
 [ 98  42  65  20  70]
 [ 35  89  70  47  57]]
[24 11 15 20 35]
